import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useLayoutEffect, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton } from '../components/AppButton';
import { AppTextInput } from '../components/AppTextInput';
import { strings } from '../constants/appStrings';
import { RootStackParamList } from '../navigation/types';
import { useWordsStore } from '../stores/useWordsStore';
import { useAppColors } from '../theme/colors';
import { isDuplicateWord, validateWord } from '../utils/validation';
type Props = NativeStackScreenProps<RootStackParamList, 'AddEditWord'>;
export function AddEditWordScreen({ navigation, route }: Props) { const c = useAppColors(); const { words, addWord, updateWord } = useWordsStore(); const existing = words.find((w) => w.id === route.params?.wordId); const [term, setTerm] = useState(existing?.term ?? ''); const [translation, setTranslation] = useState(existing?.translation ?? ''); const [exampleSentence, setExample] = useState(existing?.exampleSentence ?? ''); const [note, setNote] = useState(existing?.note ?? ''); const [error, setError] = useState<string>(); useLayoutEffect(() => navigation.setOptions({ title: existing ? strings.editWord : strings.addWord }), [navigation, existing]); const save = async () => { const validation = validateWord(term, translation); if (!validation.valid) { setError(validation.message); return; } if (isDuplicateWord(term, words, existing?.id)) { setError(strings.duplicate); Alert.alert(strings.duplicate); return; } const draft = { term, translation, exampleSentence, note }; try { if (existing) await updateWord(existing.id, draft); else await addWord(draft); navigation.goBack(); } catch { Alert.alert('Kayıt yapılamadı', 'Lütfen tekrar deneyin.'); } }; return <SafeAreaView edges={['bottom']} style={[styles.safe, { backgroundColor: c.background }]}><KeyboardAvoidingView style={styles.safe} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.form}><AppTextInput label={strings.term} value={term} onChangeText={(v) => { setTerm(v); setError(undefined); }} autoCapitalize="none" error={error} /><AppTextInput label={strings.translation} value={translation} onChangeText={(v) => { setTranslation(v); setError(undefined); }} error={error} /><AppTextInput label={strings.example} value={exampleSentence} onChangeText={setExample} multiline /><AppTextInput label={strings.note} value={note} onChangeText={setNote} multiline /><View style={styles.actions}><AppButton title={strings.save} onPress={() => void save()} /><AppButton title={strings.cancel} variant="secondary" onPress={() => navigation.goBack()} /></View></ScrollView></KeyboardAvoidingView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, form: { padding: 16, gap: 18 }, actions: { gap: 10, marginTop: 6 } });
