import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Ionicons } from '@expo/vector-icons';
import { BackHandler, StyleSheet, Text, View } from 'react-native';
import { useEffect } from 'react';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton } from '../components/AppButton';
import { AppCard } from '../components/AppCard';
import { EmptyState } from '../components/EmptyState';
import { strings } from '../constants/appStrings';
import { RootStackParamList } from '../navigation/types';
import { usePracticeStore } from '../stores/usePracticeStore';
import { useWordsStore } from '../stores/useWordsStore';
import { useAppColors } from '../theme/colors';
type Props = NativeStackScreenProps<RootStackParamList, 'Practice'>;
export function PracticeScreen({ navigation }: Props) {
  const c = useAppColors(); const words = useWordsStore((s) => s.words); const recordAnswer = useWordsStore((s) => s.recordAnswer);
  const { queue, index, answerShown, lastAnswer, summary, answer, next } = usePracticeStore(); const id = queue[index]; const word = words.find((w) => w.id === id);
  useEffect(() => { const sub = BackHandler.addEventListener('hardwareBackPress', () => true); return () => sub.remove(); }, []);
  if (!word) return <SafeAreaView style={[styles.safe, { backgroundColor: c.background }]}><EmptyState title="Kart bulunamadı" body="Ana ekrana dönüp tekrar başlatın." /><AppButton title={strings.backHome} onPress={() => navigation.popToTop()} /></SafeAreaView>;
  const respond = async (known: boolean) => { if (answerShown) return; answer(word.id, known); await recordAnswer(word.id, known); };
  const advance = () => { if (index >= queue.length - 1) navigation.replace('PracticeSummary', summary); else next(); };
  return <SafeAreaView edges={['bottom']} style={[styles.safe, { backgroundColor: c.background }]}><View style={styles.progressRow}><Text style={[styles.progressLabel, { color: c.muted }]}>Kart {index + 1}</Text><Text style={[styles.progressLabel, { color: c.muted }]}>{queue.length}</Text></View><View style={[styles.track, { backgroundColor: c.surfaceMuted }]}><View style={[styles.progressFill, { backgroundColor: c.primary, width: `${((index + 1) / queue.length) * 100}%` }]} /></View><View style={styles.center}><AppCard><View style={styles.cardBody}><View style={[styles.wordIcon, { backgroundColor: c.primarySoft }]}><Ionicons name="language-outline" size={21} color={c.primary} /></View><Text style={[styles.kicker, { color: c.muted }]}>BU KELİMEYİ BİLİYOR MUSUN?</Text><Text numberOfLines={4} adjustsFontSizeToFit style={[styles.term, { color: c.text }]}>{word.term}</Text>{answerShown ? <View style={[styles.answer, { backgroundColor: lastAnswer ? c.successSoft : c.dangerSoft }]}><Text style={[styles.answerLabel, { color: lastAnswer ? c.success : c.danger }]}>TÜRKÇE KARŞILIĞI</Text><Text style={[styles.translation, { color: c.text }]}>{word.translation}</Text>{word.exampleSentence ? <Text style={[styles.detail, { color: c.muted }]}>“{word.exampleSentence}”</Text> : null}{word.note ? <Text style={[styles.detail, { color: c.muted }]}>Not: {word.note}</Text> : null}</View> : <Text style={[styles.hint, { color: c.muted }]}>Cevabı görmek için seçimini yap</Text>}</View></AppCard></View><View style={styles.buttons}>{answerShown ? <AppButton title={index >= queue.length - 1 ? strings.finish : strings.next} icon="arrow-forward" onPress={advance} /> : <View style={styles.responseRow}><View style={styles.flex}><AppButton title={strings.dontKnow} variant="danger" icon="close" onPress={() => void respond(false)} /></View><View style={styles.flex}><AppButton title={strings.know} variant="success" icon="checkmark" onPress={() => void respond(true)} /></View></View>}</View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, padding: 18 }, progressRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 }, progressLabel: { fontSize: 12, fontWeight: '600' }, track: { height: 5, borderRadius: 3, overflow: 'hidden' }, progressFill: { height: '100%', borderRadius: 3 }, center: { flex: 1, justifyContent: 'center' }, cardBody: { minHeight: 390, alignItems: 'center', justifyContent: 'center', padding: 8 }, wordIcon: { width: 46, height: 46, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginBottom: 20 }, kicker: { fontSize: 10, fontWeight: '700', letterSpacing: 1.3, marginBottom: 13 }, term: { fontSize: 40, fontWeight: '700', letterSpacing: -1.1, textAlign: 'center' }, hint: { marginTop: 24, fontSize: 13 }, answer: { width: '100%', alignItems: 'center', marginTop: 30, padding: 17, borderRadius: 17, gap: 9 }, answerLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, translation: { fontSize: 25, textAlign: 'center', fontWeight: '700' }, detail: { fontSize: 14, lineHeight: 20, textAlign: 'center' }, buttons: { paddingBottom: 4 }, responseRow: { flexDirection: 'row', gap: 10 }, flex: { flex: 1 } });
