import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Ionicons } from '@expo/vector-icons';
import { StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton } from '../components/AppButton';
import { AppCard } from '../components/AppCard';
import { strings } from '../constants/appStrings';
import { RootStackParamList } from '../navigation/types';
import { usePracticeStore } from '../stores/usePracticeStore';
import { useWordsStore } from '../stores/useWordsStore';
import { useAppColors } from '../theme/colors';
type Props = NativeStackScreenProps<RootStackParamList, 'PracticeSummary'>;
export function PracticeSummaryScreen({ navigation, route }: Props) { const c = useAppColors(); const words = useWordsStore((s) => s.words); const includeLearned = useWordsStore((s) => s.includeLearned); const start = usePracticeStore((s) => s.start); const remaining = words.filter((w) => !w.isLearned).length; const rows = [[strings.shown, route.params.shown], [strings.known, route.params.known], [strings.unknown, route.params.unknown], [strings.remaining, remaining]] as const; const restart = () => { const pool = words.filter((w) => includeLearned || !w.isLearned); if (!pool.length) { navigation.popToTop(); return; } start(words, includeLearned); navigation.replace('Practice'); }; return <SafeAreaView edges={['bottom']} style={[styles.safe, { backgroundColor: c.background }]}><View style={styles.center}><View style={[styles.icon, { backgroundColor: c.successSoft }]}><Ionicons name="checkmark" size={30} color={c.success} /></View><Text style={[styles.title, { color: c.text }]}>Tekrar tamamlandı</Text><Text style={[styles.subtitle, { color: c.muted }]}>Bugünkü çalışmanın kısa özeti</Text><AppCard>{rows.map(([label, value]) => <View key={label} style={[styles.row, { borderBottomColor: c.border }]}><Text style={{ color: c.muted }}>{label}</Text><Text style={[styles.value, { color: c.text }]}>{value}</Text></View>)}</AppCard></View><View style={styles.actions}><AppButton title={strings.startPractice} icon="refresh" onPress={restart} /><AppButton title={strings.backHome} variant="secondary" onPress={() => navigation.popToTop()} /></View></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, padding: 18 }, center: { flex: 1, justifyContent: 'center' }, icon: { width: 60, height: 60, borderRadius: 20, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: 18 }, title: { textAlign: 'center', fontSize: 27, fontWeight: '700', letterSpacing: -0.6 }, subtitle: { textAlign: 'center', fontSize: 14, marginTop: 7, marginBottom: 24 }, row: { minWidth: 260, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 15, borderBottomWidth: StyleSheet.hairlineWidth }, value: { fontSize: 18, fontWeight: '700' }, actions: { gap: 10 } });
